export const AllProducts: Products = [
  {
    id: "jsjjertecjhe47eu3",
    name: "Black Hoodie",
    desc: " a timeless addition to your wardrobe. Crafted with comfort and style in mind, this hoodie is the epitome of understated cool. The rich black hue complements any outfit, making it the perfect choice for both casual outings and laid-back evenings. Its premium cotton blend ensures a soft touch against your skin, while the adjustable hood adds an extra layer of coziness. Whether you're heading out for a brisk walk or simply relaxing at home, our Black Hoodie is the ultimate go-to piece. Elevate your fashion game with this essential staple today.",
    img: "/img/black-hoodie.jpg",
    price: 64.9,
    sizes: ["s", "m", "l", "xl"],
    numReviews: 12,
    rating: 4.2,
    category: "hoodie",
  },
  {
    id: "jhjkrsjioeiriogjejrie",
    name: "White Face-Cap",
    desc: "a must-have accessory that effortlessly combines style and sun protection. Designed with a clean and timeless aesthetic, this cap adds a touch of sophistication to any outfit. The crisp white color pairs seamlessly with various looks, making it a versatile choice for both urban adventures and outdoor escapades. Crafted with high-quality materials, the cap offers a comfortable fit and features an adjustable strap for a personalized feel. Whether you're strolling through the city streets or enjoying a sunny day at the park, our White Face Cap is your go-to accessory for staying cool and looking sharp. Embrace the elegance of simplicity – get your White Face Cap today.",
    img: "/img/cap.jpg",
    price: 29.9,
    sizes: ["s", "m", "l", "xl"],
    category: "cap",
    numReviews: 1,
    rating: 3,
  },
  {
    id: "jhsazjdfjkjskjfjweoiw",
    name: "Hat",
    desc: "Introducing our classic White Face Cap – a must-have accessory that effortlessly combines style and sun protection. Designed with a clean and timeless aesthetic, this cap adds a touch of sophistication to any outfit. The crisp white color pairs seamlessly with various looks, making it a versatile choice for both urban adventures and outdoor escapades. Crafted with high-quality materials, the cap offers a comfortable fit and features an adjustable strap for a personalized feel. Whether you're strolling through the city streets or enjoying a sunny day at the park, our White Face Cap is your go-to accessory for staying cool and looking sharp. Embrace the elegance of simplicity – get your White Face Cap today.",
    img: "/img/hat.jpg",
    price: 24.9,
    sizes: ["s", "m", "l", "xl"],
    category: "hat",
    numReviews: 0,
    rating: 4.8,
  },
  {
    id: "jhrjerekrjgioejo",
    name: "Demin",
    desc: "Introducing our Denim Jacket – a timeless staple that effortlessly fuses rugged style with everyday comfort. Crafted with meticulous attention to detail, this jacket showcases the iconic denim fabric that never goes out of fashion. With its versatile design, it seamlessly complements various outfits, making it a must-have addition to your wardrobe.",
    img: "/img/jean-jacket.jpg",
    price: 26.9,
    sizes: ["s", "m", "l", "xl"],
    category: "demin",
    numReviews: 7,
    rating: 2.3,
  },
  {
    id: "hsehfiwigejoiowajiej",
    name: "White T Shirt",
    desc: "With its classic design and impeccable fit, our T-shirt effortlessly transitions from casual outings to relaxed evenings. The timeless color palette complements any outfit, making it a reliable go-to piece for effortless fashion. Whether you're pairing it with jeans for a laid-back look or dressing it up with a blazer, this T-shirt is your versatile canvas for self-expression.",
    img: "/img/t-shirt.jpg",
    price: 29.9,
    sizes: ["s", "m", "l", "xl"],
    category: "shirt",
    numReviews: 3,
    rating: 4,
  },
  {
    id: "uejhrjhfejrfwjiajefiwjeoijfwidjve",
    name: "Grey hoodie",
    desc: "Introducing our sleek and versatile Black Hoodie – a timeless addition to your wardrobe. Crafted with comfort and style in mind, this hoodie is the epitome of understated cool. The rich black hue complements any outfit, making it the perfect choice for both casual outings and laid-back evenings. Its premium cotton blend ensures a soft touch against your skin, while the adjustable hood adds an extra layer of coziness. Whether you're heading out for a brisk walk or simply relaxing at home, our Black Hoodie is the ultimate go-to piece. Elevate your fashion game with this essential staple today.",
    img: "/img/grey-hoodie.jpg",
    price: 24.9,
    sizes: ["s", "m", "l", "xl"],
    category: "hoodie",
    numReviews: 12,
    rating: 2,
  },
  {
    id: "hjrsjhfjwfewuijiukwjoiaes",
    name: "Face Cap",
    desc: "Introducing our classic White Face Cap – a must-have accessory that effortlessly combines style and sun protection. Designed with a clean and timeless aesthetic, this cap adds a touch of sophistication to any outfit. The crisp white color pairs seamlessly with various looks, making it a versatile choice for both urban adventures and outdoor escapades. Crafted with high-quality materials, the cap offers a comfortable fit and features an adjustable strap for a personalized feel. Whether you're strolling through the city streets or enjoying a sunny day at the park, our White Face Cap is your go-to accessory for staying cool and looking sharp. Embrace the elegance of simplicity – get your White Face Cap today.",
    img: "/img/face-cap.jpg",
    price: 28.9,
    sizes: ["s", "m", "l", "xl"],
    category: "cap",
    numReviews: 1,
    rating: 4.1,
  },
];
